### ISSUE TITLE
Globally installed jscs doesn't see locally installed plugins

### ISSUE THREAD

**Issue by zxqfox** [jscs-dev/node-jscs#863]
How to repeat:
```
mkdir test && cd test
echo '{"name":"testing","private":true}' > package.json
npm init
npm i -g jscs
npm i jscs-jsdoc
rm -rf ./node_modules/jscs
echo '{"plugins":["jscs-jsdoc"]}' > .jscsrc
touch file.js
mkdir subtest && cd subtest
jscs -c ../test/.jscsrc ../test/file.js
```

output:
```
# `plugin` should be a function
```

But if we do:
```
cd ..
npm i jscs
cd subtest
../node_modules/.bin/jscs -c ../.jscsrc ../file.js
```

We will get:
```
No code style errors found.
```

Can it be fixed? I guess we can try to search from provided configuration (`.jscsrc`) to, probably, manifest file (`package.json`) or root, as well as `node` doing it:
```
$ node -p 'module.paths'
[ '/home/alex/repos/node_modules',
  '/home/alex/node_modules',
  '/home/node_modules',
  '/node_modules' ]
```

p.s. It forces me to install all plugins from different projects outside of a development server. It's a pain when I mount some folders via AFP/Samba and SublimeLinter failing with `Cannot find module 'jscs-plugin'`. Another way is to fix SublimeLinter plugin itself, but I'm not sure it's an easy task, and also there are a lot of another IDE plugins that can use plugins so I believe it should be fixed in jscs.

**Comment by markelog** [comment]
/cc @mdevils 

Want to give it a shot?

**Comment by mdevils** [comment]
Well... Actually I would not allow installing jscs globally... Global installation is the well-known bad practice.

**Comment by mdevils** [comment]
Seems like there are some path problems. Will take a look.

**Comment by markelog** [comment]
> not allow installing jscs globally

That is what we recommend - http://jscs.info/overview.html :-), i can see how it might cause problems though.

**Comment by mdevils** [comment]
Wow, I didn't know we recommend that O_O

**Comment by mikesherov** [comment]
I do think that global install of JSCS is a good thing, in line with the other linters and CLI tools.

Perhaps we should include "relative to package.json" in our list of ways to find where plugins exist? Or consult with how JSHint or ESLint accomplish this?

**Comment by zxqfox** [comment]
@mikesherov @mdevils Also different plugins recommends that https://packagecontrol.io/packages/SublimeLinter-jscs

You can see that jshint requires that too https://packagecontrol.io/packages/SublimeLinter-jshint

**Comment by markelog** [comment]
> Wow, I didn't know we recommend that O_O

That is universally acceptable way - 
https://github.com/jshint/jshint/blob/master/package.json#L66
https://github.com/eslint/eslint/blob/master/package.json#L82
and for a lot of programs alike. And as @zxqfox mentioned, IDE plugins usually ask you do it, although i have no idea why.

It could do harm with obvious ways though.

> Or consult with how JSHint or ESLint accomplish this?

I think there is not many things you could do, usually discrepancies between global and local installs are low, especially for our kind of tools. `grunt-cli` example is only acceptable way to handle this, if we want to handle this. 

But i don't think this is that much of a big deal, i think people know about this problem and why it is like that.

**Comment by mrjoelkemp** [comment]
> IDE plugins usually ask you do it, although i have no idea why.

A few (not impossible to solve) reasons:

1. It's easier than assuming all packages are installed in `node_modules` of the currently opened project. 2. It's also less prone to breakages if the binary's filename changes.
3. In the sublime text case, workspaces allow multiple projects in a single editor instance which adds complexity to determining which node_modules folder is the right one (since the ST api isn't great for knowing the currently active project of all opened projects)

**Comment by markelog** [comment]
> A few (not impossible to solve) reasons:

I would install own version of jscs with the package, without depending on local one, or make local dependency a requirement, it's weird if project has ".jscsrc" config but don't depend on jscs

**Comment by zxqfox** [comment]
@mrjoelkemp 

But anyway there is a difference between `jshint` and `jscs` in plugins and `additionalRules` option. Even if some linter have plugin I'm not sure that this problem is resolved.

And I have an idea.
What if we make some `jscs-cli` package that will install global `jscs` binary and will use locally installed `jscs` in projects.

**Comment by zxqfox** [comment]
@mrjoelkemp I'm not sure that you can't determine what project it is if you saving a file. You can go through directories up to the root and look for `.jscsrc` or `package.json` file. But it would break a deal if somebody creates `.jscsrc` in inner project directories.

**Comment by markelog** [comment]
> What if we make some jscs-cli package that will install global jscs binary and will use locally installed jscs in projects.

That's what i said in https://github.com/jscs-dev/node-jscs/issues/863issuecomment-69349848. I think we should have a real life issue before doing that stuff

**Comment by zxqfox** [comment]
@markelog We will have a lot of troubles with rules deprecations, different versions (2.0?) and for now I can't use plugins without global installation. Is it real life issue?

**Comment by markelog** [comment]
> We will 

That's speculative

> now I can't use plugins without global installation

That's a different issue

**Comment by zxqfox** [comment]
Yup. Is there an issue in 2.0 milestone about that troubles? Probably it's time to make it to move this discussion there.

**Comment by markelog** [comment]
No, feel free to create one

**Comment by markelog** [comment]
Maaan, now gotta be more convincing then that! This is not a feature, this is a bug and big one!

**Comment by markelog** [comment]
Fixed via https://github.com/jscs-dev/node-jscs/commit/4008ba26fba862b6dbf55de6a32118a35a0f2133
